title: ""
description: ""
url: "https://embracingauthenticity.co.uk"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM

future: true
permalink: /:title/

plugins:
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - netlify.toml
  - node_modules
  - vendor
  - .bundle
  - .jekyll-cache
  - _site
